// Code generated by protoc-gen-go. DO NOT EDIT.
// source: landlord.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_NoError           ResultCode = 0
	ResultCode_AgentNotFound     ResultCode = 1
	ResultCode_AgentAddressError ResultCode = 2
	ResultCode_GameNotFound      ResultCode = 3
)

var ResultCode_name = map[int32]string{
	0: "NoError",
	1: "AgentNotFound",
	2: "AgentAddressError",
	3: "GameNotFound",
}

var ResultCode_value = map[string]int32{
	"NoError":           0,
	"AgentNotFound":     1,
	"AgentAddressError": 2,
	"GameNotFound":      3,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{0}
}

type JsonREQ struct {
	JsonType             int32    `protobuf:"varint,1,opt,name=JsonType,proto3" json:"JsonType,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonREQ) Reset()         { *m = JsonREQ{} }
func (m *JsonREQ) String() string { return proto.CompactTextString(m) }
func (*JsonREQ) ProtoMessage()    {}
func (*JsonREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{0}
}

func (m *JsonREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonREQ.Unmarshal(m, b)
}
func (m *JsonREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonREQ.Marshal(b, m, deterministic)
}
func (m *JsonREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonREQ.Merge(m, src)
}
func (m *JsonREQ) XXX_Size() int {
	return xxx_messageInfo_JsonREQ.Size(m)
}
func (m *JsonREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonREQ.DiscardUnknown(m)
}

var xxx_messageInfo_JsonREQ proto.InternalMessageInfo

func (m *JsonREQ) GetJsonType() int32 {
	if m != nil {
		return m.JsonType
	}
	return 0
}

func (m *JsonREQ) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type JsonACK struct {
	JsonType             int32    `protobuf:"varint,1,opt,name=JsonType,proto3" json:"JsonType,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonACK) Reset()         { *m = JsonACK{} }
func (m *JsonACK) String() string { return proto.CompactTextString(m) }
func (*JsonACK) ProtoMessage()    {}
func (*JsonACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{1}
}

func (m *JsonACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonACK.Unmarshal(m, b)
}
func (m *JsonACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonACK.Marshal(b, m, deterministic)
}
func (m *JsonACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonACK.Merge(m, src)
}
func (m *JsonACK) XXX_Size() int {
	return xxx_messageInfo_JsonACK.Size(m)
}
func (m *JsonACK) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonACK.DiscardUnknown(m)
}

var xxx_messageInfo_JsonACK proto.InternalMessageInfo

func (m *JsonACK) GetJsonType() int32 {
	if m != nil {
		return m.JsonType
	}
	return 0
}

func (m *JsonACK) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type TestACK struct {
	Dummy                string   `protobuf:"bytes,1,opt,name=Dummy,proto3" json:"Dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestACK) Reset()         { *m = TestACK{} }
func (m *TestACK) String() string { return proto.CompactTextString(m) }
func (*TestACK) ProtoMessage()    {}
func (*TestACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{2}
}

func (m *TestACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestACK.Unmarshal(m, b)
}
func (m *TestACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestACK.Marshal(b, m, deterministic)
}
func (m *TestACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestACK.Merge(m, src)
}
func (m *TestACK) XXX_Size() int {
	return xxx_messageInfo_TestACK.Size(m)
}
func (m *TestACK) XXX_DiscardUnknown() {
	xxx_messageInfo_TestACK.DiscardUnknown(m)
}

var xxx_messageInfo_TestACK proto.InternalMessageInfo

func (m *TestACK) GetDummy() string {
	if m != nil {
		return m.Dummy
	}
	return ""
}

type SubscribeChannelREQ struct {
	Channel              string   `protobuf:"bytes,1,opt,name=Channel,proto3" json:"Channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelREQ) Reset()         { *m = SubscribeChannelREQ{} }
func (m *SubscribeChannelREQ) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelREQ) ProtoMessage()    {}
func (*SubscribeChannelREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{3}
}

func (m *SubscribeChannelREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelREQ.Unmarshal(m, b)
}
func (m *SubscribeChannelREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelREQ.Marshal(b, m, deterministic)
}
func (m *SubscribeChannelREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelREQ.Merge(m, src)
}
func (m *SubscribeChannelREQ) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelREQ.Size(m)
}
func (m *SubscribeChannelREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelREQ.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelREQ proto.InternalMessageInfo

func (m *SubscribeChannelREQ) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type SubscribeChannelACK struct {
	Channel              string   `protobuf:"bytes,1,opt,name=Channel,proto3" json:"Channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelACK) Reset()         { *m = SubscribeChannelACK{} }
func (m *SubscribeChannelACK) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelACK) ProtoMessage()    {}
func (*SubscribeChannelACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{4}
}

func (m *SubscribeChannelACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelACK.Unmarshal(m, b)
}
func (m *SubscribeChannelACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelACK.Marshal(b, m, deterministic)
}
func (m *SubscribeChannelACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelACK.Merge(m, src)
}
func (m *SubscribeChannelACK) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelACK.Size(m)
}
func (m *SubscribeChannelACK) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelACK.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelACK proto.InternalMessageInfo

func (m *SubscribeChannelACK) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type SvcStatusACK struct {
	SvcID                string   `protobuf:"bytes,1,opt,name=SvcID,proto3" json:"SvcID,omitempty"`
	UserCount            int32    `protobuf:"varint,2,opt,name=UserCount,proto3" json:"UserCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SvcStatusACK) Reset()         { *m = SvcStatusACK{} }
func (m *SvcStatusACK) String() string { return proto.CompactTextString(m) }
func (*SvcStatusACK) ProtoMessage()    {}
func (*SvcStatusACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{5}
}

func (m *SvcStatusACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvcStatusACK.Unmarshal(m, b)
}
func (m *SvcStatusACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvcStatusACK.Marshal(b, m, deterministic)
}
func (m *SvcStatusACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvcStatusACK.Merge(m, src)
}
func (m *SvcStatusACK) XXX_Size() int {
	return xxx_messageInfo_SvcStatusACK.Size(m)
}
func (m *SvcStatusACK) XXX_DiscardUnknown() {
	xxx_messageInfo_SvcStatusACK.DiscardUnknown(m)
}

var xxx_messageInfo_SvcStatusACK proto.InternalMessageInfo

func (m *SvcStatusACK) GetSvcID() string {
	if m != nil {
		return m.SvcID
	}
	return ""
}

func (m *SvcStatusACK) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

type ServerInfo struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{6}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PingACK struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingACK) Reset()         { *m = PingACK{} }
func (m *PingACK) String() string { return proto.CompactTextString(m) }
func (*PingACK) ProtoMessage()    {}
func (*PingACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{7}
}

func (m *PingACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingACK.Unmarshal(m, b)
}
func (m *PingACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingACK.Marshal(b, m, deterministic)
}
func (m *PingACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingACK.Merge(m, src)
}
func (m *PingACK) XXX_Size() int {
	return xxx_messageInfo_PingACK.Size(m)
}
func (m *PingACK) XXX_DiscardUnknown() {
	xxx_messageInfo_PingACK.DiscardUnknown(m)
}

var xxx_messageInfo_PingACK proto.InternalMessageInfo

type LoginREQ struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	TokenReq             []byte   `protobuf:"bytes,3,opt,name=TokenReq,proto3" json:"TokenReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginREQ) Reset()         { *m = LoginREQ{} }
func (m *LoginREQ) String() string { return proto.CompactTextString(m) }
func (*LoginREQ) ProtoMessage()    {}
func (*LoginREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{8}
}

func (m *LoginREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginREQ.Unmarshal(m, b)
}
func (m *LoginREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginREQ.Marshal(b, m, deterministic)
}
func (m *LoginREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginREQ.Merge(m, src)
}
func (m *LoginREQ) XXX_Size() int {
	return xxx_messageInfo_LoginREQ.Size(m)
}
func (m *LoginREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginREQ.DiscardUnknown(m)
}

var xxx_messageInfo_LoginREQ proto.InternalMessageInfo

func (m *LoginREQ) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginREQ) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginREQ) GetTokenReq() []byte {
	if m != nil {
		return m.TokenReq
	}
	return nil
}

type LoginACK struct {
	Result               ResultCode  `protobuf:"varint,1,opt,name=Result,proto3,enum=proto.ResultCode" json:"Result,omitempty"`
	Server               *ServerInfo `protobuf:"bytes,2,opt,name=Server,proto3" json:"Server,omitempty"`
	TokenAck             int32       `protobuf:"varint,3,opt,name=TokenAck,proto3" json:"TokenAck,omitempty"`
	GameSvcID            string      `protobuf:"bytes,4,opt,name=GameSvcID,proto3" json:"GameSvcID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginACK) Reset()         { *m = LoginACK{} }
func (m *LoginACK) String() string { return proto.CompactTextString(m) }
func (*LoginACK) ProtoMessage()    {}
func (*LoginACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{9}
}

func (m *LoginACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginACK.Unmarshal(m, b)
}
func (m *LoginACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginACK.Marshal(b, m, deterministic)
}
func (m *LoginACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginACK.Merge(m, src)
}
func (m *LoginACK) XXX_Size() int {
	return xxx_messageInfo_LoginACK.Size(m)
}
func (m *LoginACK) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginACK.DiscardUnknown(m)
}

var xxx_messageInfo_LoginACK proto.InternalMessageInfo

func (m *LoginACK) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_NoError
}

func (m *LoginACK) GetServer() *ServerInfo {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *LoginACK) GetTokenAck() int32 {
	if m != nil {
		return m.TokenAck
	}
	return 0
}

func (m *LoginACK) GetGameSvcID() string {
	if m != nil {
		return m.GameSvcID
	}
	return ""
}

type VerifyREQ struct {
	GameToken            string   `protobuf:"bytes,1,opt,name=GameToken,proto3" json:"GameToken,omitempty"`
	GameSvcID            string   `protobuf:"bytes,2,opt,name=GameSvcID,proto3" json:"GameSvcID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyREQ) Reset()         { *m = VerifyREQ{} }
func (m *VerifyREQ) String() string { return proto.CompactTextString(m) }
func (*VerifyREQ) ProtoMessage()    {}
func (*VerifyREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{10}
}

func (m *VerifyREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyREQ.Unmarshal(m, b)
}
func (m *VerifyREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyREQ.Marshal(b, m, deterministic)
}
func (m *VerifyREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyREQ.Merge(m, src)
}
func (m *VerifyREQ) XXX_Size() int {
	return xxx_messageInfo_VerifyREQ.Size(m)
}
func (m *VerifyREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyREQ.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyREQ proto.InternalMessageInfo

func (m *VerifyREQ) GetGameToken() string {
	if m != nil {
		return m.GameToken
	}
	return ""
}

func (m *VerifyREQ) GetGameSvcID() string {
	if m != nil {
		return m.GameSvcID
	}
	return ""
}

type VerifyACK struct {
	Result               ResultCode `protobuf:"varint,1,opt,name=Result,proto3,enum=proto.ResultCode" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VerifyACK) Reset()         { *m = VerifyACK{} }
func (m *VerifyACK) String() string { return proto.CompactTextString(m) }
func (*VerifyACK) ProtoMessage()    {}
func (*VerifyACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{11}
}

func (m *VerifyACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyACK.Unmarshal(m, b)
}
func (m *VerifyACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyACK.Marshal(b, m, deterministic)
}
func (m *VerifyACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyACK.Merge(m, src)
}
func (m *VerifyACK) XXX_Size() int {
	return xxx_messageInfo_VerifyACK.Size(m)
}
func (m *VerifyACK) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyACK.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyACK proto.InternalMessageInfo

func (m *VerifyACK) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_NoError
}

//后端服务持有，如game
type ClientID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SvcID                string   `protobuf:"bytes,2,opt,name=SvcID,proto3" json:"SvcID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientID) Reset()         { *m = ClientID{} }
func (m *ClientID) String() string { return proto.CompactTextString(m) }
func (*ClientID) ProtoMessage()    {}
func (*ClientID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{12}
}

func (m *ClientID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientID.Unmarshal(m, b)
}
func (m *ClientID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientID.Marshal(b, m, deterministic)
}
func (m *ClientID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientID.Merge(m, src)
}
func (m *ClientID) XXX_Size() int {
	return xxx_messageInfo_ClientID.Size(m)
}
func (m *ClientID) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientID.DiscardUnknown(m)
}

var xxx_messageInfo_ClientID proto.InternalMessageInfo

func (m *ClientID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ClientID) GetSvcID() string {
	if m != nil {
		return m.SvcID
	}
	return ""
}

//后端关闭agent持有的与client的session
type CloseClientACK struct {
	ID                   []int64  `protobuf:"varint,1,rep,packed,name=ID,proto3" json:"ID,omitempty"`
	All                  bool     `protobuf:"varint,2,opt,name=All,proto3" json:"All,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseClientACK) Reset()         { *m = CloseClientACK{} }
func (m *CloseClientACK) String() string { return proto.CompactTextString(m) }
func (*CloseClientACK) ProtoMessage()    {}
func (*CloseClientACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{13}
}

func (m *CloseClientACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseClientACK.Unmarshal(m, b)
}
func (m *CloseClientACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseClientACK.Marshal(b, m, deterministic)
}
func (m *CloseClientACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseClientACK.Merge(m, src)
}
func (m *CloseClientACK) XXX_Size() int {
	return xxx_messageInfo_CloseClientACK.Size(m)
}
func (m *CloseClientACK) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseClientACK.DiscardUnknown(m)
}

var xxx_messageInfo_CloseClientACK proto.InternalMessageInfo

func (m *CloseClientACK) GetID() []int64 {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *CloseClientACK) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

//agent关闭与client的session后通知对应的后端服务
type ClientClosedACK struct {
	ID                   *ClientID `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ClientClosedACK) Reset()         { *m = ClientClosedACK{} }
func (m *ClientClosedACK) String() string { return proto.CompactTextString(m) }
func (*ClientClosedACK) ProtoMessage()    {}
func (*ClientClosedACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{14}
}

func (m *ClientClosedACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientClosedACK.Unmarshal(m, b)
}
func (m *ClientClosedACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientClosedACK.Marshal(b, m, deterministic)
}
func (m *ClientClosedACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientClosedACK.Merge(m, src)
}
func (m *ClientClosedACK) XXX_Size() int {
	return xxx_messageInfo_ClientClosedACK.Size(m)
}
func (m *ClientClosedACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientClosedACK.DiscardUnknown(m)
}

var xxx_messageInfo_ClientClosedACK proto.InternalMessageInfo

func (m *ClientClosedACK) GetID() *ClientID {
	if m != nil {
		return m.ID
	}
	return nil
}

//用于将client的消息转发到后台服务，以及将后台服务的消息转发给client
type TransmitACK struct {
	MsgID                uint32   `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
	ClientID             int64    `protobuf:"varint,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientIDList         []int64  `protobuf:"varint,4,rep,packed,name=ClientIDList,proto3" json:"ClientIDList,omitempty"`
	All                  bool     `protobuf:"varint,5,opt,name=All,proto3" json:"All,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitACK) Reset()         { *m = TransmitACK{} }
func (m *TransmitACK) String() string { return proto.CompactTextString(m) }
func (*TransmitACK) ProtoMessage()    {}
func (*TransmitACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c7e11019a60a25, []int{15}
}

func (m *TransmitACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitACK.Unmarshal(m, b)
}
func (m *TransmitACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitACK.Marshal(b, m, deterministic)
}
func (m *TransmitACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitACK.Merge(m, src)
}
func (m *TransmitACK) XXX_Size() int {
	return xxx_messageInfo_TransmitACK.Size(m)
}
func (m *TransmitACK) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitACK.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitACK proto.InternalMessageInfo

func (m *TransmitACK) GetMsgID() uint32 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *TransmitACK) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *TransmitACK) GetClientID() int64 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *TransmitACK) GetClientIDList() []int64 {
	if m != nil {
		return m.ClientIDList
	}
	return nil
}

func (m *TransmitACK) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterType((*JsonREQ)(nil), "proto.JsonREQ")
	proto.RegisterType((*JsonACK)(nil), "proto.JsonACK")
	proto.RegisterType((*TestACK)(nil), "proto.TestACK")
	proto.RegisterType((*SubscribeChannelREQ)(nil), "proto.SubscribeChannelREQ")
	proto.RegisterType((*SubscribeChannelACK)(nil), "proto.SubscribeChannelACK")
	proto.RegisterType((*SvcStatusACK)(nil), "proto.SvcStatusACK")
	proto.RegisterType((*ServerInfo)(nil), "proto.ServerInfo")
	proto.RegisterType((*PingACK)(nil), "proto.PingACK")
	proto.RegisterType((*LoginREQ)(nil), "proto.LoginREQ")
	proto.RegisterType((*LoginACK)(nil), "proto.LoginACK")
	proto.RegisterType((*VerifyREQ)(nil), "proto.VerifyREQ")
	proto.RegisterType((*VerifyACK)(nil), "proto.VerifyACK")
	proto.RegisterType((*ClientID)(nil), "proto.ClientID")
	proto.RegisterType((*CloseClientACK)(nil), "proto.CloseClientACK")
	proto.RegisterType((*ClientClosedACK)(nil), "proto.ClientClosedACK")
	proto.RegisterType((*TransmitACK)(nil), "proto.TransmitACK")
}

func init() { proto.RegisterFile("landlord.proto", fileDescriptor_d4c7e11019a60a25) }

var fileDescriptor_d4c7e11019a60a25 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0xdd, 0x24, 0x93, 0x34, 0x4d, 0x0c, 0x48, 0x11, 0x42, 0x6a, 0xb5, 0xa7, 0xc2,
	0xa1, 0x54, 0x41, 0xe2, 0x8a, 0x8c, 0x53, 0x2a, 0xd3, 0x0f, 0x85, 0x4d, 0xda, 0x13, 0x17, 0x27,
	0xde, 0x04, 0xab, 0xce, 0x6e, 0xd9, 0x5d, 0x47, 0xca, 0xaf, 0xe0, 0xce, 0xaf, 0x45, 0xfb, 0x65,
	0x53, 0x04, 0x07, 0x38, 0x65, 0xdf, 0xe4, 0xbd, 0xb7, 0xf3, 0x66, 0xd6, 0xd0, 0x2f, 0x33, 0x9a,
	0x97, 0x8c, 0xe7, 0xa7, 0x0f, 0x9c, 0x49, 0x16, 0x85, 0xfa, 0x07, 0xbd, 0x87, 0xd6, 0x27, 0xc1,
	0x28, 0x3e, 0xff, 0x1c, 0xbd, 0x80, 0xb6, 0x3a, 0xce, 0x77, 0x0f, 0x64, 0xe4, 0x1d, 0x7b, 0x27,
	0x21, 0xae, 0x71, 0x34, 0x82, 0x56, 0xc2, 0xa8, 0x24, 0x54, 0x8e, 0xfc, 0x63, 0xef, 0xa4, 0x87,
	0x1d, 0x74, 0x06, 0x71, 0x72, 0xf9, 0x9f, 0x06, 0x47, 0xd0, 0x9a, 0x13, 0x21, 0x95, 0xc1, 0x33,
	0x08, 0x27, 0xd5, 0x66, 0xb3, 0xd3, 0xea, 0x0e, 0x36, 0x00, 0xbd, 0x81, 0xa7, 0xb3, 0x6a, 0x21,
	0x96, 0xbc, 0x58, 0x90, 0xe4, 0x6b, 0x46, 0x29, 0x29, 0x55, 0xbb, 0xca, 0xd1, 0x20, 0x4b, 0x77,
	0xf0, 0x4f, 0x02, 0xe5, 0xfe, 0x77, 0xc1, 0x07, 0xe8, 0xcd, 0xb6, 0xcb, 0x99, 0xcc, 0x64, 0x25,
	0x6c, 0x1f, 0xb3, 0xed, 0x32, 0x9d, 0xb8, 0x3e, 0x34, 0x88, 0x5e, 0x42, 0xe7, 0x56, 0x10, 0x9e,
	0xb0, 0xca, 0x86, 0x08, 0x71, 0x53, 0x40, 0x67, 0x00, 0x33, 0xc2, 0xb7, 0x84, 0xa7, 0x74, 0xc5,
	0xa2, 0x3e, 0xf8, 0xe9, 0xd4, 0xca, 0xfd, 0x74, 0x1a, 0x45, 0xb0, 0x37, 0x65, 0xdc, 0xc9, 0xf4,
	0x19, 0x75, 0xa0, 0x35, 0x2d, 0xe8, 0x3a, 0x4e, 0x2e, 0xd1, 0x17, 0x68, 0x5f, 0xb1, 0x75, 0x41,
	0x6d, 0xae, 0x3b, 0xc2, 0x45, 0xc1, 0xa8, 0x6b, 0xd3, 0x42, 0x35, 0xdf, 0x69, 0x99, 0xc9, 0x15,
	0xe3, 0x1b, 0x6d, 0xd4, 0xc1, 0x35, 0x56, 0xff, 0xcd, 0xd9, 0x3d, 0xa1, 0x98, 0x7c, 0x1b, 0x05,
	0x7a, 0xc0, 0x35, 0x46, 0x3f, 0x3c, 0x6b, 0xaf, 0xb2, 0xbd, 0x82, 0x7d, 0x4c, 0x44, 0x55, 0x4a,
	0xed, 0xde, 0x1f, 0x0f, 0xcd, 0x7b, 0x38, 0x35, 0xc5, 0x84, 0xe5, 0x04, 0x5b, 0x82, 0xa2, 0x9a,
	0x48, 0xfa, 0xb6, 0x6e, 0x4d, 0x6d, 0x72, 0x62, 0x4b, 0xa8, 0xaf, 0x8f, 0x97, 0xf7, 0xfa, 0xfa,
	0x10, 0xd7, 0x58, 0xcd, 0xed, 0x22, 0xdb, 0x10, 0x33, 0xd1, 0x3d, 0xdd, 0x77, 0x53, 0x40, 0x17,
	0xd0, 0xb9, 0x23, 0xbc, 0x58, 0xed, 0x54, 0x76, 0x4b, 0xd5, 0x52, 0x9b, 0xbe, 0x29, 0x3c, 0x36,
	0xf2, 0x7f, 0x37, 0x7a, 0xe7, 0x8c, 0xfe, 0x2d, 0x25, 0x3a, 0x83, 0x76, 0x52, 0x16, 0x84, 0xca,
	0x74, 0xa2, 0xd7, 0x66, 0xb6, 0x1e, 0x60, 0x3f, 0x9d, 0x34, 0x0f, 0xc1, 0xff, 0xe5, 0x21, 0xa0,
	0x31, 0xf4, 0x93, 0x92, 0x09, 0x62, 0x64, 0xea, 0x3a, 0xa7, 0x0b, 0xac, 0x6e, 0x00, 0x41, 0x5c,
	0x96, 0x5a, 0xd5, 0xc6, 0xea, 0x88, 0xc6, 0x70, 0x68, 0xe8, 0x5a, 0x99, 0x2b, 0xd1, 0x51, 0x7d,
	0x59, 0x77, 0x7c, 0x68, 0xfb, 0x73, 0x9d, 0x28, 0x17, 0xf4, 0xdd, 0x83, 0xee, 0x9c, 0x67, 0x54,
	0x6c, 0x0a, 0xf7, 0x79, 0x5c, 0x8b, 0xb5, 0xd5, 0x1c, 0x60, 0x03, 0xd4, 0x7b, 0xb9, 0x16, 0xeb,
	0x49, 0x26, 0x33, 0xf7, 0x65, 0x59, 0xa8, 0x96, 0xe2, 0xfc, 0xf4, 0x52, 0x02, 0xdc, 0x24, 0x45,
	0xd0, 0x73, 0xe7, 0xab, 0x42, 0xc8, 0xd1, 0x9e, 0xee, 0xfd, 0x51, 0xcd, 0xa5, 0x08, 0xeb, 0x14,
	0xaf, 0x6f, 0x01, 0x9a, 0x09, 0x46, 0x5d, 0x68, 0xdd, 0xb0, 0x73, 0xce, 0x19, 0x1f, 0x3c, 0x89,
	0x86, 0x70, 0x10, 0xaf, 0x09, 0x95, 0x37, 0x4c, 0x7e, 0x64, 0x15, 0xcd, 0x07, 0x5e, 0xf4, 0x1c,
	0x86, 0xba, 0x14, 0xe7, 0x39, 0x27, 0x42, 0x18, 0xa6, 0x1f, 0x0d, 0xa0, 0xa7, 0xb6, 0x56, 0x13,
	0x83, 0xc5, 0xbe, 0x0e, 0xff, 0xf6, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xaf, 0x41, 0x89,
	0xa4, 0x04, 0x00, 0x00,
}
